variable "common" {}
variable "resource_group_name" {}
variable "tags" {}
variable "random" {}
variable "postgresql_flexible_server" {}
variable "postgresql_authentication" {}
variable "postgresql_flexible_database" {}
variable "vnet" {}
variable "subnet" {}
