# =============================================================================
# GitHub Actions - Terraform Compliance ワークフロー例
# =============================================================================
# このファイルは、GitHub Actions での terraform-compliance の実行例です。
#
# 使用方法:
#   1. このファイルを .github/workflows/terraform-compliance.yml にコピー
#   2. 必要に応じてトリガーやパスを調整
#   3. Azure 認証用のシークレットを設定
# =============================================================================

name: Terraform Compliance

on:
  push:
    branches:
      - main
      - develop
    paths:
      - 'envs/**'
      - 'modules/**'
      - 'compliance/**'
  pull_request:
    branches:
      - main
    paths:
      - 'envs/**'
      - 'modules/**'
      - 'compliance/**'
  # 手動実行を許可
  workflow_dispatch:

env:
  # Terraform のバージョン
  TF_VERSION: '1.6.0'
  # 作業ディレクトリ
  WORKING_DIR: 'envs/dev'

jobs:
  # ==========================================================================
  # Job 1: Terraform Validate & Format
  # ==========================================================================
  validate:
    name: Validate & Format
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      # フォーマットチェック
      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      # 構文検証
      - name: Terraform Init (for validate)
        run: terraform init -backend=false
        working-directory: ${{ env.WORKING_DIR }}

      - name: Terraform Validate
        run: terraform validate
        working-directory: ${{ env.WORKING_DIR }}

  # ==========================================================================
  # Job 2: terraform test (機能テスト)
  # ==========================================================================
  terraform-test:
    name: Terraform Test
    runs-on: ubuntu-latest
    needs: validate

    # Azure 認証が必要な場合はこのセクションのコメントを解除
    # env:
    #   ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
    #   ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
    #   ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
    #   ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Terraform Init
        run: terraform init -backend=false
        working-directory: ${{ env.WORKING_DIR }}

      - name: Terraform Test
        run: terraform test -verbose
        working-directory: ${{ env.WORKING_DIR }}

  # ==========================================================================
  # Job 3: terraform-compliance (コンプライアンステスト)
  # ==========================================================================
  compliance:
    name: Compliance Test
    runs-on: ubuntu-latest
    needs: validate

    # Azure 認証が必要な場合はこのセクションのコメントを解除
    # env:
    #   ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
    #   ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
    #   ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
    #   ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}
          # terraform show の出力をラップしないようにする
          terraform_wrapper: false

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          version: "latest"

      - name: Terraform Init
        run: terraform init -backend=false
        working-directory: ${{ env.WORKING_DIR }}

      # Plan を生成（実際の Azure 接続なしでも一部のテストは可能）
      - name: Generate Terraform Plan
        run: |
          terraform plan -out=tfplan.binary
          terraform show -json tfplan.binary > tfplan.json
        working-directory: ${{ env.WORKING_DIR }}
        continue-on-error: true

      # コンプライアンステストを実行（uvx で直接実行）
      - name: Run Compliance Tests
        run: |
          uvx terraform-compliance \
            -f compliance/features \
            -p ${{ env.WORKING_DIR }}/tfplan.json
        continue-on-error: true

      # クリティカルなテストのみを必須にする場合
      - name: Run Critical Compliance Tests
        run: |
          uvx terraform-compliance \
            -f compliance/features \
            -p ${{ env.WORKING_DIR }}/tfplan.json \
            --tags @critical

  # ==========================================================================
  # Job 4: セキュリティスキャン (オプション)
  # ==========================================================================
  security-scan:
    name: Security Scan
    runs-on: ubuntu-latest
    needs: validate

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # tflint
      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v4

      - name: Init TFLint
        run: tflint --init

      - name: Run TFLint
        run: tflint -f compact
        working-directory: ${{ env.WORKING_DIR }}
        continue-on-error: true

      # Checkov
      - name: Run Checkov
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: ${{ env.WORKING_DIR }}
          soft_fail: true
          output_format: cli
          output_bc_ids: true

  # ==========================================================================
  # Job 5: 結果サマリー
  # ==========================================================================
  summary:
    name: Summary
    runs-on: ubuntu-latest
    needs: [validate, terraform-test, compliance, security-scan]
    if: always()

    steps:
      - name: Check Results
        run: |
          echo "## テスト結果サマリー" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "| テスト | 結果 |" >> $GITHUB_STEP_SUMMARY
          echo "|--------|------|" >> $GITHUB_STEP_SUMMARY
          echo "| Validate | ${{ needs.validate.result }} |" >> $GITHUB_STEP_SUMMARY
          echo "| Terraform Test | ${{ needs.terraform-test.result }} |" >> $GITHUB_STEP_SUMMARY
          echo "| Compliance | ${{ needs.compliance.result }} |" >> $GITHUB_STEP_SUMMARY
          echo "| Security Scan | ${{ needs.security-scan.result }} |" >> $GITHUB_STEP_SUMMARY
