variable "common" {}
variable "resource_group_name" {}
variable "tags" {}
variable "app_service" {}
variable "allowed_cidr" {}
variable "app_service_plan" {}
variable "subnet" {}
variable "identity" {}
variable "frontdoor_profile" {}
variable "app_settings" {}
variable "allowed_origins" {}
