variable "common" {}
variable "resource_group_name" {}
variable "tags" {}
variable "frontdoor_security_policy" {}
variable "frontdoor_firewall_policy" {}
variable "frontdoor_firewall_custom_rule" {}
variable "frontdoor_profile" {}
variable "frontdoor_custom_domain" {}
variable "allowed_cidr" {}
